# I disagree with this cop. I feel that @_var_name is better for memoization
# than @var_name, to make it very clear you don't want people to use that
# variable directly. Maybe this is a page out of my Python book.
Naming/MemoizedInstanceVariableName:
  Enabled: False

# I do not find that block length impacts readability to the point that I need
# to worry about it, so I'll disable that check.
Metrics/BlockLength:
  Enabled: False
