language: ruby
rvm:
  - 2.4.1
cache: bundler

script:
 - bundle exec rake build

before_deploy:
  - bundle exec rake test

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  region: $AWS_S3_REGION
  skip_cleanup: true
  local_dir: _site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
