title_short: mide
title_long: Mark Ide Jr
email: hello@cranstonide.com
url: https://www.mide.io
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title.html
strict_front_matter: true

# Twitter Plugin
twitter_handle: cranstonide

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Rakefile
  - README.md
  - vendor # Travis CI

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-collection

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      toc: true
