title_short: mide
title_long: Mark Ide Jr
email: hello@cranstonide.com
url: https://www.mide.io
markdown: redcarpet

exclude:
  - Gemfile
  - Gemfile.lck
  - Rakefile
  - README.md
  - s3_website.yml
  - vendor # Travis CI

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
