name_short: mide
name_long: Mark Ide Jr
email: hello@cranstonide.com
url: https://www.mide.io
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title.html
strict_front_matter: true
source_url: https://github.com/mide/mide.io

# Twitter Plugin
twitter_handle: cranstonide

# Jekyll Tidy Plugin
jekyll_tidy:
  compress_html: false
  exclude:
    - "*.txt"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Rakefile
  - README.md
  - vendor # Travis CI

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-twitter-collection

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      toc: true
