title_short: mide
title_long: Mark Ide Jr
email: hello@cranstonide.com
url: https://www.mide.io
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor # Travis CI

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
