author: Mark Ide Jr
email: hello@cranstonide.com
markdown: kramdown
name: Mark Ide Jr
name_short: mide
permalink: /blog/:year/:month/:day/:title.html
source_url: https://github.com/mide/mide.io
strict_front_matter: true
url: https://www.mide.io
description: The blog of Mark Ide Jr.

# Clean up code (see jekyll/jekyll#920 on GitHub)
include:
  - "_pages"

# Jekyll Tidy Plugin
jekyll_tidy:
  compress_html: false
  exclude:
    - "*.txt"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Rakefile
  - README.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-toc

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      toc: true
