---
name: Lint Code Base

on: push

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Lint Codebase
        uses: github/super-linter@v3
        env:
          VALIDATE_CSS: false
          VALIDATE_HTML: false

  html_validate:
    name: Lint Resulting HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Set up Ruby 2.7 Environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Bundler and Gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build Jekyll Website
        run: bundle exec jekyll build
      - name: Lint Resulting HTML
        uses: github/super-linter@v3
        env:
          FILTER_REGEX_EXCLUDE: .*/_site/(assets|css)/.*
          FILTER_REGEX_INCLUDE: .*/_site/.*
