name: Test Suite

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Set up Ruby 2.7 Environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Bundler and Gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll Website
        run: bundle exec jekyll build

      - name: Run HTML Validity Tests
        run: bundle exec rake test:html

      - name: Run Remote Link Tests
        run: bundle exec rake remote:links

      - name: Run Remote EXIF Data Tests
        run: bundle exec rake remote:exif
